name: PWA Health Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      base_url:
        description: "Target base URL"
        required: false
        default: "https://wentian-clean.vercel.app"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run PWA health script
        env:
          BASE_URL: ${{ github.event.inputs.base_url || 'https://wentian-clean.vercel.app' }}
        run: node scripts/pwa-health.mjs
