name: r5-smoke

on:
  schedule:
    - cron: "0 */6 * * *"   # 每6小時
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Ping R5 (/_r5/ping) with retry
        env:
          R5_BASE: ${{ vars.R5_BASE }}          # 例：https://<your-app>.vercel.app
          R5_TOKEN: ${{ secrets.R5_TOKEN }}     # 若需要授權就填；沒用到可移除 header
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i"
            curl -fsS -X POST "$R5_BASE/_r5/ping" \
              -H "Authorization: Bearer ${R5_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{}' && exit 0 || sleep 3
          done
          echo "Ping failed after retries" >&2
          exit 1

      - name: Diag (/_r5/diag)
        env:
          R5_BASE: ${{ vars.R5_BASE }}
        run: |
          curl -fsS "$R5_BASE/_r5/diag" | head -c 2000 || (echo "diag failed" >&2; exit 1)
