name: r5-smoke
on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE: https://wentian-clean.vercel.app
    steps:
      - name: Ping /_models/health
        run: |
          set -e
          test "$(curl -s -o /dev/null -w '%{http_code}' $BASE/_models/health)" = "200"

      - name: Chat 2+2 via /_models/chat (no model to use server default)
        run: |
          set -e
          payload='{"messages":[{"role":"user","content":"2+2"}]}'
          code=$(curl -sS -o /tmp/chat.json -w "%{http_code}" -X POST \
            -H "content-type: application/json" -d "$payload" "$BASE/_models/chat")
          echo "code=$code"
          cat /tmp/chat.json || true
          [ "$code" -ge 200 ] && [ "$code" -lt 300 ]

      - name: Ping /_r5/health
        run: |
          set -e
          test "$(curl -s -o /dev/null -w '%{http_code}' $BASE/_r5/health)" = "200"
