name: r5-sql-migrate

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:
    inputs:
      path:
        description: 'SQL 相對路徑（留空=自動偵測變更）'
        required: false
        default: ''

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run SQL
        env:
          DB: ${{ secrets.SUPABASE_DB_URL }}
          INPATH: ${{ github.event.inputs.path }}
        run: |
          set -euo pipefail

          run_one () {
            f="$1"
            echo "==> applying $f"
            psql "$DB" -v ON_ERROR_STOP=1 -f "$f"
          }

          if [ -n "$INPATH" ]; then
            test -f "$INPATH" || { echo "file not found: $INPATH" >&2; exit 1; }
            run_one "$INPATH"
            exit 0
          fi

          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -E '^supabase/migrations/.*\.sql$' || true)
          if [ -z "$CHANGED" ]; then
            echo "no changed sql under supabase/migrations"
            exit 0
          fi

          echo "$CHANGED" | while read -r f; do
            run_one "$f"
          done
