name: r5-workflow-audit

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "app/**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: github
