name: r5-workflow-doctor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 改用維護中的 actionlint 動作（避免 rhysd/actionlint@v1 找不到 / 404）
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check          # 在 Checks 顯示結果
          fail_on_error: true             # 有錯就 fail，確保 workflow 準確卡關

      # yamllint 先設成不阻斷（有錯也先讓 R5 能跑完）
      - name: yamllint (non-blocking)
        uses: ibiqlik/action-yamllint@v3
        continue-on-error: true
        with:
          file_or_dir: ".github/workflows"
          # 簡單規則，避免常見瑣碎警告卡關
          config_data: |
            extends: default
            rules:
              line-length: disable
              trailing-spaces: disable
