name: r5-workflow-doctor

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"   # UTC 每日例行

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  doctor:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 範例：R5 健檢 + 重試機制
      - name: R5 ping (with retry)
        env:
          R5_BASE: ${{ vars.R5_BASE }}          # 或 secrets / env，依你現況
          R5_TOKEN: ${{ secrets.R5_TOKEN }}     # 如需權杖
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i..."
            curl -fsS -X POST "$R5_BASE/_r5/ping" \
              -H "Authorization: Bearer ${R5_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{}' && exit 0 || sleep 3
          done
          echo "R5 ping failed after retries." >&2
          exit 1
