name: r5-workflow-audit

on:
  pull_request:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Workflows
    runs-on: ubuntu-latest
    # 在 push(main) 上不阻斷，把錯誤當警告；在 PR 上會用真正的狀態檢查擋住
    continue-on-error: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          filter_mode: nofilter
          fail_on_error: ${{ github.event_name == 'pull_request' }}

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows"
          format: github
          strict: true
