name: r5-workflow-audit

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install actionlint
        shell: bash
        run: |
          set -eux
          mkdir -p "$HOME/.local/bin"
          curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.sh \
          | bash -s -- -b "$HOME/.local/bin" v1.7.3
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          actionlint -version

      - name: actionlint
        run: actionlint -color

      - name: Summary
        run: echo "audit passed ✅"
