name: r5-workflow-doctor

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # GitHub Actions 工作流程語法檢查（官方 action）
      - name: actionlint (GitHub Actions linter)
        uses: rhysd/actionlint@v1
        with:
          version: "1.7.3"

      # YAML 靜態檢查
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          strict: true
