name: r5 workflow doctor

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go (for actionlint)
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install actionlint (official way)
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
          echo "${HOME}/go/bin" >> "$GITHUB_PATH"
          actionlint -version

      - name: Run actionlint (non-blocking)
        continue-on-error: true
        run: |
          actionlint -color

      - name: Install yamllint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint
          yamllint --version

      - name: Run yamllint (non-blocking)
        continue-on-error: true
        run: |
          yamllint -s .
