name: r5-workflow-doctor

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - ".github/workflows/r5-workflow-doctor.yml"

jobs:
  doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Install fixed actionlint binary (v1.7.1) ---
      - name: Install actionlint
        shell: bash
        run: |
          set -euo pipefail
          ver="1.7.1"
          url="https://github.com/rhysd/actionlint/releases/download/v${ver}/actionlint_${ver}_linux_amd64.tar.gz"
          curl -fsSL "$url" -o /tmp/actionlint.tgz
          sudo tar -C /usr/local/bin -xzf /tmp/actionlint.tgz actionlint
          actionlint -version

      # --- Install yamllint (pin 1.35.1) ---
      - name: Install yamllint
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "yamllint==1.35.1"
          yamllint --version

      - name: Lint workflows with actionlint
        run: |
          actionlint -color -shellcheck= -format=github

      - name: Lint YAML files with yamllint
        run: |
          yamllint -c <(cat <<'YAML'
          extends: default
          rules:
            line-length: disable
            truthy: disable
          YAML
          ) \
          .github/workflows

      - name: Diagnosis summary
        run: echo "Doctor OK ✅"
