name: r5-workflow-doctor

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/r5-workflow-doctor.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/r5-workflow-doctor.yml"

permissions:
  contents: read

jobs:
  doctor:
    runs-on: ubuntu-latest
    env:
      R5_BASE: ${{ secrets.R5_BASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: R5 ping (with retry)
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${R5_BASE:-}" ]; then
            echo "::error::R5_BASE is empty. Set repo secret R5_BASE to your endpoint (e.g. https://wentian-clean.vercel.app/api/r5)"
            exit 1
          fi
          url="${R5_BASE%/}/ping"
          echo "Pinging ${url/https:\/\//https://***}/ …"
          for i in {1..3}; do
            if curl -fsSL "$url" >/dev/null; then
              echo "R5 ping OK"
              exit 0
            fi
            echo "Retry $i/3…"
            sleep 3
          done
          echo "::error::R5 ping failed: $url"
          exit 1

      # 你其它的檢查/腳本可以接在下面
