name: r5-workflow-doctor

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Env / tools quick check
        run: |
          echo "Runner: ${{ runner.os }} ($(uname -a))"
          echo "PATH=$PATH"
          which bash || true
          which curl || true

      - name: Install actionlint (same as audit)
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash -o /tmp/dl.sh
          bash /tmp/dl.sh -b "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          actionlint --version

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint --version

      - name: Dry-run audits
        run: |
          actionlint -color -shellcheck=
          yamllint -s .
