name: r5-workflow-audit

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安裝 actionlint（裝在 $HOME/bin，然後寫入 GITHUB_PATH）
      - name: Install actionlint
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash -o /tmp/dl.sh
          bash /tmp/dl.sh -b "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Run actionlint
        shell: bash
        run: |
          actionlint -color -shellcheck=

      # 安裝 yamllint（用 apt 最穩）
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Run yamllint
        run: |
          yamllint -s .
