name: r5-workflow-doctor

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "app/**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ 使用 reviewdog/action-actionlint（穩定、免安裝腳本）
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning

      # 可選：YAML 檔也順便檢查
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: github
