name: r5-workflow-doctor

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  r5-doctor:
    name: R5 Doctor (non-blocking lint decoupled)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # === 這裡放你原本的 R5 健檢 / 連通 / 通報 步驟 ===
      # 範例：
      # - name: ping R5
      #   run: |
      #     curl -fsSL -X POST "$R5_BASE/_r5/ping" -H "Authorization: Bearer ${{ secrets.R5_TOKEN }}"

  lint:   # 把 Lint 拆開，且不阻擋主線
    name: Lint (actionlint + yamllint)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows"
          format: github
          strict: true
