name: upgrader

on:
  workflow_dispatch:
    inputs:
      jobType:
        description: "Job type"
        required: true
        default: "fuceti_init"
      plan:
        description: "Plan JSON"
        required: false
        default: "{}"
      jobId:
        description: "Job ID"
        required: true
      notifyURL:
        description: "Notify URL"
        required: true
      notifyToken:
        description: "Notify Token"
        required: true
      branch:
        description: "Target branch"
        required: true
        default: "main"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo inputs (smoke)
        run: |
          echo "jobType=${{ inputs.jobType }}"
          echo "plan=${{ inputs.plan }}"
          echo "jobId=${{ inputs.jobId }}"
          echo "branch=${{ inputs.branch }}"
