name: upgrader
on:
  workflow_dispatch:
    inputs:
      jobType:    { required: true,  default: fuceti_init }
      plan:       { required: false, default: "{}" }
      jobId:      { required: true }
      notifyURL:  { required: true }
      notifyToken:{ required: true }
      branch:     { required: true,  default: main }

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "jobType=${{ inputs.jobType }}"
          echo "plan=${{ inputs.plan }}"
          echo "jobId=${{ inputs.jobId }}"
          echo "branch=${{ inputs.branch }}"
