name: vercel-promote
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["r5-auto-merge"]
    types: [completed]

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Find latest READY preview
        id: find
        run: |
          set -e
          DEPLOY_ID=$(curl -fsS \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "x-vercel-team-id: $VERCEL_ORG_ID" \
            "https://api.vercel.com/v13/deployments?projectId=$VERCEL_PROJECT_ID&state=READY&target=preview&limit=1" \
            | jq -r '.deployments[0].uid')
          test -n "$DEPLOY_ID"
          echo "id=$DEPLOY_ID" >> $GITHUB_OUTPUT

      - name: Promote → production (retry)
        run: |
          set -e
          code=$(./scripts/ci-retry.sh 5 2 curl -sS -o /tmp/promote.json -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "x-vercel-team-id: $VERCEL_ORG_ID" \
            "https://api.vercel.com/v13/deployments/${{ steps.find.outputs.id }}/promote?target=production")
          echo "HTTP=$code"; cat /tmp/promote.json || true
          [[ "$code" == "200" || "$code" == "201" ]]
