name: vercel-promote
on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["r5-auto-merge"]
    types: [completed]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Promote latest READY preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -e
          LATEST=$(curl -fsSL "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&state=READY&limit=1" \
            -H "Authorization: Bearer $VERCEL_TOKEN" | jq -r '.deployments[0].uid')
          test "$LATEST" != "null" -a -n "$LATEST"
          curl -fsSL -X POST "https://api.vercel.com/v13/deployments/${LATEST}/promote?force=true" \
            -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" -d "{}"
          echo "promoted=$LATEST" >> $GITHUB_STEP_SUMMARY
